<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Testing" />
    <ProjectReference Include="..\..\src\CarparkAvailability.AppHost\CarparkAvailability.AppHost.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Aspire.Hosting.ApplicationModel" />
    <Using Include="Aspire.Hosting.Testing" />
  </ItemGroup>

</Project>
